//! Explicit presentation metadata for built-in ribbon commands.
//!
//! This file is catalog input, not ribbon output. Ribbon layout code identifies
//! commands; labels, categories and command icons are resolved from this table.

use super::{CommandCategory, CommandMetadata, CommandVariantMetadata};
use crate::ui::icon_catalog::IconId;

macro_rules! builtin_icon {
    ($key:literal, $path:literal) => {
        Some(IconId::Builtin {
            key: $key,
            svg: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), $path)),
        })
    };
}

const fn builtin(
    id: &'static str,
    label: &'static str,
    icon: Option<IconId>,
    category: CommandCategory,
) -> CommandMetadata {
    CommandMetadata {
        id,
        aliases: &[],
        label,
        description: None,
        icon,
        category,
    }
}

const fn variant(
    invocation: &'static str,
    label: &'static str,
    icon: Option<IconId>,
) -> CommandVariantMetadata {
    CommandVariantMetadata {
        invocation,
        label,
        icon,
    }
}

pub(super) const BUILTIN_VARIANTS: &[CommandVariantMetadata] = &[
    variant(
        "OBJECTSCALE ADD",
        "Add Current Scale",
        builtin_icon!("OBJECTSCALE_ADD", "/assets/icons/add_scale.svg"),
    ),
    variant(
        "OBJECTSCALE DELETE",
        "Delete Current Scale",
        builtin_icon!("OBJECTSCALE_DELETE", "/assets/icons/add_scale.svg"),
    ),
    variant(
        "VIEW FRONT",
        "Front",
        builtin_icon!("VIEW_FRONT", "/assets/icons/view_front.svg"),
    ),
    variant(
        "VIEW ISO",
        "Iso",
        builtin_icon!("VIEW_ISO", "/assets/icons/view_iso.svg"),
    ),
    variant(
        "VIEW RIGHT",
        "Right",
        builtin_icon!("VIEW_RIGHT", "/assets/icons/view_right.svg"),
    ),
    variant(
        "VIEW TOP",
        "Top",
        builtin_icon!("VIEW_TOP", "/assets/icons/view_top.svg"),
    ),
    variant(
        "VISUALSTYLES WIREFRAME2D",
        "Wireframe 2D",
        builtin_icon!("VISUALSTYLES_WIREFRAME2D", "/assets/icons/wireframe.svg"),
    ),
    variant(
        "VISUALSTYLES WIREFRAME3D",
        "Wireframe 3D",
        builtin_icon!("VISUALSTYLES_WIREFRAME3D", "/assets/icons/wireframe.svg"),
    ),
    variant(
        "VISUALSTYLES HIDDENLINE",
        "Hidden Line",
        builtin_icon!("VISUALSTYLES_HIDDENLINE", "/assets/icons/hidden.svg"),
    ),
    variant(
        "VISUALSTYLES FLATSHADED",
        "Flat Shaded",
        builtin_icon!("VISUALSTYLES_FLATSHADED", "/assets/icons/solid.svg"),
    ),
    variant(
        "VISUALSTYLES GOURAUDSHADED",
        "Gouraud Shaded",
        builtin_icon!("VISUALSTYLES_GOURAUDSHADED", "/assets/icons/solid.svg"),
    ),
    variant(
        "VISUALSTYLES FLATSHADEDWITHEDGES",
        "Flat Shaded + Edges",
        builtin_icon!(
            "VISUALSTYLES_FLATSHADEDWITHEDGES",
            "/assets/icons/solid.svg"
        ),
    ),
    variant(
        "VISUALSTYLES GOURAUDSHADEDWITHEDGES",
        "Gouraud Shaded + Edges",
        builtin_icon!(
            "VISUALSTYLES_GOURAUDSHADEDWITHEDGES",
            "/assets/icons/solid.svg"
        ),
    ),
    variant("ZOOM DYNAMIC", "Zoom Dynamic", Some(IconId::Zoom)),
    variant("ZOOM EXTENTS", "Zoom Extents", Some(IconId::ZoomExtents)),
    variant(
        "ZOOM IN",
        "Zoom In",
        builtin_icon!("ZOOM_IN", "/assets/icons/zoom_in.svg"),
    ),
    variant(
        "ZOOM OUT",
        "Zoom Out",
        builtin_icon!("ZOOM_OUT", "/assets/icons/zoom_out.svg"),
    ),
    variant(
        "ZOOM WINDOW",
        "Zoom Window",
        builtin_icon!("ZOOM_WINDOW", "/assets/icons/zoom_window.svg"),
    ),
];

pub(super) const BUILTIN_PRESENTATION: &[CommandMetadata] = &[
    builtin(
        "3DORBIT",
        "3D Orbit",
        builtin_icon!("3DORBIT", "/assets/icons/orbit.svg"),
        CommandCategory::View,
    ),
    builtin(
        "ABOUT",
        "About",
        builtin_icon!("ABOUT", "/assets/icons/about.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "ADCENTER",
        "Design\nCenter",
        builtin_icon!("ADCENTER", "/assets/icons/design_center.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "ADJUST",
        "Adjust",
        builtin_icon!("ADJUST", "/assets/icons/xadjust.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "ALIASEDIT",
        "Edit Aliases",
        builtin_icon!("ALIASEDIT", "/assets/icons/edit_aliases.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "ALIGN",
        "Align",
        builtin_icon!("ALIGN", "/assets/icons/modify_align.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNBOTTOM",
        "Align Bottom",
        builtin_icon!("ALIGNBOTTOM", "/assets/icons/align_bottom.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNHCENTER",
        "Align Horizontal Centers",
        builtin_icon!("ALIGNHCENTER", "/assets/icons/align_hcenter.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNLEFT",
        "Align Left",
        builtin_icon!("ALIGNLEFT", "/assets/icons/align_left.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNRIGHT",
        "Align Right",
        builtin_icon!("ALIGNRIGHT", "/assets/icons/align_right.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNTOP",
        "Align Top",
        builtin_icon!("ALIGNTOP", "/assets/icons/align_top.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ALIGNVCENTER",
        "Align Vertical Centers",
        builtin_icon!("ALIGNVCENTER", "/assets/icons/align_vcenter.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ANNORESET",
        "Sync Scale Positions",
        builtin_icon!("ANNORESET", "/assets/icons/sync.svg"),
        CommandCategory::Annotate,
    ),
    builtin("ARC", "Arc", Some(IconId::Arc3Point), CommandCategory::Draw),
    builtin(
        "ARC_3P",
        "3-Point",
        Some(IconId::Arc3Point),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_CONT",
        "Continue",
        Some(IconId::ArcContinue),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_CSA",
        "Center, Start, Angle",
        Some(IconId::ArcCenterStartAngle),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_CSE",
        "Center, Start, End",
        Some(IconId::ArcCenterStartEnd),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_CSL",
        "Center, Start, Length",
        Some(IconId::ArcCenterStartLength),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SCA",
        "Start, Center, Angle",
        Some(IconId::ArcStartCenterAngle),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SCE",
        "Start, Center, End",
        Some(IconId::ArcStartCenterEnd),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SCL",
        "Start, Center, Length",
        Some(IconId::ArcStartCenterLength),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SEA",
        "Start, End, Angle",
        Some(IconId::ArcStartEndAngle),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SED",
        "Start, End, Direction",
        Some(IconId::ArcStartEndDirection),
        CommandCategory::Draw,
    ),
    builtin(
        "ARC_SER",
        "Start, End, Radius",
        Some(IconId::ArcStartEndRadius),
        CommandCategory::Draw,
    ),
    builtin(
        "AREA",
        "Area",
        builtin_icon!("AREA", "/assets/icons/area.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "ARRAYPATH",
        "Path Array",
        builtin_icon!("ARRAYPATH", "/assets/icons/array_path.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ARRAYPOLAR",
        "Polar Array",
        builtin_icon!("ARRAYPOLAR", "/assets/icons/array_polar.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ARRAYRECT",
        "Rectangular Array",
        builtin_icon!("ARRAYRECT", "/assets/icons/array_rect.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "ATTDEF",
        "Define\nAttributes",
        builtin_icon!("ATTDEF", "/assets/icons/attdef.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "ATTEDIT",
        "Edit\nAttribute",
        builtin_icon!("ATTEDIT", "/assets/icons/attedit.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "ATTMAN",
        "Manage",
        builtin_icon!("ATTMAN", "/assets/icons/attman.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "ATTSYNC",
        "Synchronize",
        builtin_icon!("ATTSYNC", "/assets/icons/attsync.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "AUDIT",
        "Audit",
        builtin_icon!("AUDIT", "/assets/icons/audit.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "AUTOCONSTRAIN",
        "Auto Constrain",
        builtin_icon!("AUTOCONSTRAIN", "/assets/icons/constrain/auto.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "BASE",
        "Set Base\nPoint",
        builtin_icon!("BASE", "/assets/icons/base_point.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "BEDIT",
        "Edit Block",
        builtin_icon!("BEDIT", "/assets/icons/edit_block.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "BLOCK",
        "Create Block",
        builtin_icon!("BLOCK", "/assets/icons/blocks/block.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "BLOCKPALETTE",
        "Block\nPalette",
        builtin_icon!("BLOCKPALETTE", "/assets/icons/blocks/insert.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "BOUNDARY",
        "Boundary",
        builtin_icon!("BOUNDARY", "/assets/icons/boundary.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "BOX",
        "Box",
        builtin_icon!("BOX", "/assets/icons/model/box.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "BREAK",
        "Break",
        builtin_icon!("BREAK", "/assets/icons/modify_break.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "BREAKATPOINT",
        "Break at Point",
        builtin_icon!("BREAKATPOINT", "/assets/icons/modify_breakatpoint.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "CASCADE",
        "Cascade",
        builtin_icon!("CASCADE", "/assets/icons/cascade.svg"),
        CommandCategory::View,
    ),
    builtin(
        "CCONSTRAINT",
        "Coincident",
        builtin_icon!("CCONSTRAINT", "/assets/icons/constrain/coincident.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "CENTERDISASSOCIATE",
        "Disassociate Center Object",
        builtin_icon!("CENTERDISASSOCIATE", "/assets/icons/line.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "CENTERLINE",
        "Center Line",
        builtin_icon!("CENTERLINE", "/assets/icons/line.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "CENTERMARK",
        "Center Mark",
        builtin_icon!("CENTERMARK", "/assets/icons/line.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "CENTERREASSOCIATE",
        "Reassociate Center Object",
        builtin_icon!("CENTERREASSOCIATE", "/assets/icons/line.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "CENTERRESET",
        "Reset Center Object",
        builtin_icon!("CENTERRESET", "/assets/icons/line.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "CHAMFER",
        "Chamfer",
        builtin_icon!("CHAMFER", "/assets/icons/chamfer.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "CHAMFEREDGE",
        "Chamfer",
        builtin_icon!("CHAMFEREDGE", "/assets/icons/model/chamfer.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "CIRCLE",
        "Circle",
        Some(IconId::Circle),
        CommandCategory::Draw,
    ),
    builtin(
        "CIRCLE_2P",
        "2-Point",
        Some(IconId::Circle2Point),
        CommandCategory::Draw,
    ),
    builtin(
        "CIRCLE_3P",
        "3-Point",
        Some(IconId::Circle3Point),
        CommandCategory::Draw,
    ),
    builtin(
        "CIRCLE_CD",
        "Center, Diameter",
        Some(IconId::CircleDiameter),
        CommandCategory::Draw,
    ),
    builtin(
        "CIRCLE_TTR",
        "Tan, Tan, Radius",
        Some(IconId::CircleTangentRadius),
        CommandCategory::Draw,
    ),
    builtin(
        "CIRCLE_TTT",
        "Tan, Tan, Tan",
        Some(IconId::CircleThreeTangents),
        CommandCategory::Draw,
    ),
    builtin(
        "CONE",
        "Cone",
        builtin_icon!("CONE", "/assets/icons/model/cone.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "CONTENTBROWSER",
        "Content\nBrowser",
        builtin_icon!("CONTENTBROWSER", "/assets/icons/content_browser.svg"),
        CommandCategory::Insert,
    ),
    builtin("COPY", "Copy", Some(IconId::Copy), CommandCategory::Modify),
    builtin(
        "COPYBASE",
        "Copy with Base Point",
        Some(IconId::CopyClipboard),
        CommandCategory::Clipboard,
    ),
    builtin(
        "COPYCLIP",
        "Copy",
        Some(IconId::CopyClipboard),
        CommandCategory::Clipboard,
    ),
    builtin(
        "CUI",
        "User\nInterface",
        builtin_icon!("CUI", "/assets/icons/user_interface.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "CUIEXPORT",
        "Export",
        builtin_icon!("CUIEXPORT", "/assets/icons/cui_export.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "CUIIMPORT",
        "Import",
        builtin_icon!("CUIIMPORT", "/assets/icons/cui_import.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "CUILOAD",
        "Load Partial CUI",
        builtin_icon!("CUILOAD", "/assets/icons/cui_import.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "CUTCLIP",
        "Cut",
        Some(IconId::Cut),
        CommandCategory::Clipboard,
    ),
    builtin(
        "CYLINDER",
        "Cylinder",
        builtin_icon!("CYLINDER", "/assets/icons/model/cylinder.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "DATAEXTRACTION",
        "Extract\nData",
        builtin_icon!("DATAEXTRACTION", "/assets/icons/data_extract.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DATALINK",
        "Link\nData",
        builtin_icon!("DATALINK", "/assets/icons/data_link.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DCALIGNED",
        "Aligned",
        builtin_icon!("DCALIGNED", "/assets/icons/dim_aligned.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCANGULAR",
        "Angular",
        builtin_icon!("DCANGULAR", "/assets/icons/dim_angular.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCCONVERT",
        "Convert",
        builtin_icon!("DCCONVERT", "/assets/icons/constrain/convert.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCDIAMETER",
        "Diameter",
        builtin_icon!("DCDIAMETER", "/assets/icons/dim_diameter.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCHIDE",
        "Hide",
        builtin_icon!("DCHIDE", "/assets/icons/constrain/hide_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCHIDEALL",
        "Hide All",
        builtin_icon!("DCHIDEALL", "/assets/icons/constrain/hide_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCHORIZONTAL",
        "Horizontal",
        builtin_icon!("DCHORIZONTAL", "/assets/icons/constrain/distance_x.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCLINEAR",
        "Linear",
        builtin_icon!("DCLINEAR", "/assets/icons/dim_linear.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCRADIUS",
        "Radius",
        builtin_icon!("DCRADIUS", "/assets/icons/dim_radius.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCSHOW",
        "Show",
        builtin_icon!("DCSHOW", "/assets/icons/constrain/show.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCSHOWALL",
        "Show All",
        builtin_icon!("DCSHOWALL", "/assets/icons/constrain/show_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DCVERTICAL",
        "Vertical",
        builtin_icon!("DCVERTICAL", "/assets/icons/constrain/distance_y.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "DDEDIT",
        "Edit Text",
        builtin_icon!("DDEDIT", "/assets/icons/ddedit.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DDPTYPE",
        "Point Style",
        builtin_icon!("DDPTYPE", "/assets/icons/multipoint.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "DELCONSTRAINT",
        "Delete Constraints",
        builtin_icon!("DELCONSTRAINT", "/assets/icons/constrain/delete.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "DIMALIGNED",
        "Aligned",
        builtin_icon!("DIMALIGNED", "/assets/icons/dim_aligned.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMANGULAR",
        "Angular",
        builtin_icon!("DIMANGULAR", "/assets/icons/dim_angular.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMARC",
        "Arc Length",
        builtin_icon!("DIMARC", "/assets/icons/dim_angular.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMBASELINE",
        "Baseline",
        builtin_icon!("DIMBASELINE", "/assets/icons/dim_baseline.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMBREAK",
        "Dim Break",
        builtin_icon!("DIMBREAK", "/assets/icons/dim_break.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMCONTINUE",
        "Continue",
        builtin_icon!("DIMCONTINUE", "/assets/icons/dim_continue.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMDIAMETER",
        "Diameter",
        builtin_icon!("DIMDIAMETER", "/assets/icons/dim_diameter.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMEDIT",
        "Dim Edit",
        builtin_icon!("DIMEDIT", "/assets/icons/dim_edit.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMJOGGED",
        "Jogged Radius",
        builtin_icon!("DIMJOGGED", "/assets/icons/dim_jog.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMJOGLINE",
        "Jog Line",
        builtin_icon!("DIMJOGLINE", "/assets/icons/dim_jog.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMLINEAR",
        "Linear",
        builtin_icon!("DIMLINEAR", "/assets/icons/dim_linear.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMORDINATE",
        "Ordinate",
        builtin_icon!("DIMORDINATE", "/assets/icons/dim_ordinate.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMRADIUS",
        "Radius",
        builtin_icon!("DIMRADIUS", "/assets/icons/dim_radius.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMSPACE",
        "Dim Space",
        builtin_icon!("DIMSPACE", "/assets/icons/dim_space.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIMTEDIT",
        "Dim Text Edit",
        builtin_icon!("DIMTEDIT", "/assets/icons/dim_tedit.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "DIST",
        "Distance",
        builtin_icon!("DIST", "/assets/icons/measure.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "DIVIDE",
        "Divide",
        builtin_icon!("DIVIDE", "/assets/icons/divide.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "DONUT",
        "Donut",
        builtin_icon!("DONUT", "/assets/icons/donut.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "DRAWORDER",
        "Draw Order",
        Some(IconId::DrawOrder),
        CommandCategory::Modify,
    ),
    builtin(
        "DRAWORDER_ABOVE",
        "Bring Above Objects",
        None,
        CommandCategory::Modify,
    ),
    builtin(
        "DRAWORDER_BACK",
        "Send to Back",
        None,
        CommandCategory::Modify,
    ),
    builtin(
        "DRAWORDER_FRONT",
        "Bring to Front",
        None,
        CommandCategory::Modify,
    ),
    builtin(
        "DRAWORDER_UNDER",
        "Send Under Objects",
        None,
        CommandCategory::Modify,
    ),
    builtin(
        "ECONSTRAINT",
        "Equal",
        builtin_icon!("ECONSTRAINT", "/assets/icons/constrain/equal.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "ELLIPSE",
        "Center, Axes",
        builtin_icon!("ELLIPSE", "/assets/icons/ellipse/ellipse_ctr.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "ELLIPSE_ARC",
        "Ellipse Arc",
        builtin_icon!("ELLIPSE_ARC", "/assets/icons/ellipse/ellipse_arc.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "ELLIPSE_AXIS",
        "Axis, End",
        builtin_icon!("ELLIPSE_AXIS", "/assets/icons/ellipse/ellipse_axis.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "ERASE",
        "Erase",
        Some(IconId::Erase),
        CommandCategory::Modify,
    ),
    builtin(
        "EXPLODE",
        "Explode",
        builtin_icon!("EXPLODE", "/assets/icons/explode.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "EXTEND",
        "Extend",
        builtin_icon!("EXTEND", "/assets/icons/extend.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "EXTRUDE",
        "Extrude",
        builtin_icon!("EXTRUDE", "/assets/icons/model/extrude.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "FILETAB",
        "File\nTabs",
        builtin_icon!("FILETAB", "/assets/icons/file_tabs.svg"),
        CommandCategory::View,
    ),
    builtin(
        "FILLET",
        "Fillet",
        builtin_icon!("FILLET", "/assets/icons/fillet.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "FILLETEDGE",
        "Fillet Edge",
        builtin_icon!("FILLETEDGE", "/assets/icons/model/fillet.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "FIND",
        "Find",
        builtin_icon!("FIND", "/assets/icons/find.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "FINDNONPURGEABLE",
        "Find Non-\nPurgeable Items",
        builtin_icon!("FINDNONPURGEABLE", "/assets/icons/find_nonpurgeable.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "FRAMES0",
        "Frames Off",
        builtin_icon!("FRAMES0", "/assets/icons/underlay_frames.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "FRAMES1",
        "Frames On",
        builtin_icon!("FRAMES1", "/assets/icons/underlay_frames.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "FRAMES2",
        "Frames On, Not Plotted",
        builtin_icon!("FRAMES2", "/assets/icons/underlay_frames.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "FXCONSTRAINT",
        "Fix",
        builtin_icon!("FXCONSTRAINT", "/assets/icons/constrain/fixed.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCCONCENTRIC",
        "Concentric",
        builtin_icon!("GCCONCENTRIC", "/assets/icons/constrain/concentric.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCHIDE",
        "Hide",
        builtin_icon!("GCHIDE", "/assets/icons/constrain/hide_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCHIDEALL",
        "Hide All",
        builtin_icon!("GCHIDEALL", "/assets/icons/constrain/hide_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCHORIZONTAL",
        "Horizontal",
        builtin_icon!("GCHORIZONTAL", "/assets/icons/constrain/horizontal.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCPERPENDICULAR",
        "Perpendicular",
        builtin_icon!(
            "GCPERPENDICULAR",
            "/assets/icons/constrain/perpendicular.svg"
        ),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCRESET",
        "Reset",
        builtin_icon!("GCRESET", "/assets/icons/constrain/show.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCSHOW",
        "Show",
        builtin_icon!("GCSHOW", "/assets/icons/constrain/show.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCSHOWALL",
        "Show All",
        builtin_icon!("GCSHOWALL", "/assets/icons/constrain/show_all.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GCSMOOTH",
        "Smooth",
        builtin_icon!("GCSMOOTH", "/assets/icons/constrain/smooth.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "GRADIENT",
        "Gradient",
        builtin_icon!("GRADIENT", "/assets/icons/hatch/hatch_gradient.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "GROUP",
        "Group",
        builtin_icon!("GROUP", "/assets/icons/group.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "HATCH",
        "Hatch",
        builtin_icon!("HATCH", "/assets/icons/hatch/hatch_lines.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "HATCHEDIT",
        "Edit Hatch",
        builtin_icon!("HATCHEDIT", "/assets/icons/modify_hatchedit.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "HELIX",
        "Helix",
        builtin_icon!("HELIX", "/assets/icons/helix.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "HIDEOBJECTS",
        "Hide Objects",
        None,
        CommandCategory::Selection,
    ),
    builtin(
        "HORIZONTAL",
        "Tile\nHoriz.",
        builtin_icon!("HORIZONTAL", "/assets/icons/tile_horiz.svg"),
        CommandCategory::View,
    ),
    builtin(
        "INSERT",
        "Insert Block",
        builtin_icon!("INSERT", "/assets/icons/blocks/insert.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "INTERSECT",
        "Intersect",
        builtin_icon!("INTERSECT", "/assets/icons/model/intersect.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "ISOLATEOBJECTS",
        "Isolate Objects",
        None,
        CommandCategory::Selection,
    ),
    builtin(
        "JOIN",
        "Join",
        builtin_icon!("JOIN", "/assets/icons/modify_join.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "LANDXMLIMPORT",
        "Land\nXML",
        builtin_icon!("LANDXMLIMPORT", "/assets/icons/landxml.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "LAYFRZ",
        "Layer Freeze",
        builtin_icon!("LAYFRZ", "/assets/icons/layers/layfrz.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYISO",
        "Isolate Layer",
        builtin_icon!("LAYISO", "/assets/icons/layers/layiso.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYLCK",
        "Layer Lock",
        builtin_icon!("LAYLCK", "/assets/icons/layers/laylck.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYMATCH",
        "Match Layer",
        builtin_icon!("LAYMATCH", "/assets/icons/layers/laymatch.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYMCUR",
        "Make Current",
        builtin_icon!("LAYMCUR", "/assets/icons/layers/laymcur.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYOFF",
        "Layer Off",
        builtin_icon!("LAYOFF", "/assets/icons/layers/layoff.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYON",
        "Turn All Layers On",
        builtin_icon!("LAYON", "/assets/icons/layers/layon.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYOUTTAB",
        "Layout\nTabs",
        builtin_icon!("LAYOUTTAB", "/assets/icons/layout_tabs.svg"),
        CommandCategory::View,
    ),
    builtin(
        "LAYTHW",
        "Thaw All Layers",
        builtin_icon!("LAYTHW", "/assets/icons/layers/laythw.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYULK",
        "Layer Unlock",
        builtin_icon!("LAYULK", "/assets/icons/layers/layulk.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LAYUNISO",
        "Unisolate Layers",
        builtin_icon!("LAYUNISO", "/assets/icons/layers/layuniso.svg"),
        CommandCategory::Layers,
    ),
    builtin(
        "LCONSTRAINT",
        "Colinear",
        builtin_icon!("LCONSTRAINT", "/assets/icons/constrain/colinear.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "LEADER",
        "Leader",
        builtin_icon!("LEADER", "/assets/icons/leader.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "LENGTHEN",
        "Lengthen",
        builtin_icon!("LENGTHEN", "/assets/icons/modify_lengthen.svg"),
        CommandCategory::Modify,
    ),
    builtin("LINE", "Line", Some(IconId::Line), CommandCategory::Draw),
    builtin(
        "LOFT",
        "Loft",
        builtin_icon!("LOFT", "/assets/icons/model/loft.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "MATCHPROP",
        "Match",
        builtin_icon!("MATCHPROP", "/assets/icons/match_prop.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "MEASURE",
        "Measure",
        builtin_icon!("MEASURE", "/assets/icons/measure.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "MIRROR",
        "Mirror",
        Some(IconId::Mirror),
        CommandCategory::Modify,
    ),
    builtin(
        "MLEADER",
        "MLeader",
        builtin_icon!("MLEADER", "/assets/icons/mleader.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "MLEADERADD",
        "Add Leader",
        builtin_icon!("MLEADERADD", "/assets/icons/mleader_add.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "MLEADERALIGN",
        "Align Leaders",
        builtin_icon!("MLEADERALIGN", "/assets/icons/mleader_align.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "MLEADERCOLLECT",
        "Collect Leaders",
        builtin_icon!("MLEADERCOLLECT", "/assets/icons/mleader_collect.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "MLEADERREMOVE",
        "Remove Leader",
        builtin_icon!("MLEADERREMOVE", "/assets/icons/mleader_remove.svg"),
        CommandCategory::Annotate,
    ),
    builtin("MOVE", "Move", Some(IconId::Move), CommandCategory::Modify),
    builtin(
        "MTEXT",
        "MText",
        builtin_icon!("MTEXT", "/assets/icons/mtext.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "MULTIPOINT",
        "Multiple Points",
        builtin_icon!("MULTIPOINT", "/assets/icons/multipoint.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "MVIEW",
        "Viewport",
        builtin_icon!("MVIEW", "/assets/icons/viewport.svg"),
        CommandCategory::View,
    ),
    builtin(
        "NAVVCUBE",
        "View\nCube",
        builtin_icon!("NAVVCUBE", "/assets/icons/viewcube.svg"),
        CommandCategory::View,
    ),
    builtin(
        "NCOPY",
        "Copy Nested Objects",
        builtin_icon!("NCOPY", "/assets/icons/modify_ncopy.svg"),
        CommandCategory::Modify,
    ),
    builtin("NEW", "New", Some(IconId::New), CommandCategory::File),
    builtin(
        "OBJECTSCALE",
        "Add/Delete Scales",
        builtin_icon!("OBJECTSCALE", "/assets/icons/add_scale.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "OFFSET",
        "Offset",
        builtin_icon!("OFFSET", "/assets/icons/offset.svg"),
        CommandCategory::Modify,
    ),
    builtin("OPEN", "Open", Some(IconId::Open), CommandCategory::File),
    builtin(
        "OPTIONS",
        "Options",
        Some(IconId::Options),
        CommandCategory::Manage,
    ),
    builtin(
        "OVERKILL",
        "Overkill",
        builtin_icon!("OVERKILL", "/assets/icons/overkill.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "PAGESETUP",
        "Page Setup",
        builtin_icon!("PAGESETUP", "/assets/icons/pagesetup.svg"),
        CommandCategory::File,
    ),
    builtin("PAN", "Pan", Some(IconId::Pan), CommandCategory::View),
    builtin(
        "PARALLEL",
        "Ortho",
        builtin_icon!("PARALLEL", "/assets/icons/ortho.svg"),
        CommandCategory::View,
    ),
    builtin(
        "PARAMETERS",
        "Parameters Manager",
        builtin_icon!("PARAMETERS", "/assets/icons/constrain/parameters.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "PASTEBLOCK",
        "Paste as Block",
        Some(IconId::Paste),
        CommandCategory::Clipboard,
    ),
    builtin(
        "PASTECLIP",
        "Paste",
        Some(IconId::Paste),
        CommandCategory::Clipboard,
    ),
    builtin(
        "PASTEORIG",
        "Paste to Original Coordinates",
        Some(IconId::Paste),
        CommandCategory::Clipboard,
    ),
    builtin(
        "PCONSTRAINT",
        "Parallel",
        builtin_icon!("PCONSTRAINT", "/assets/icons/constrain/parallel.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "PDFATTACH",
        "Attach PDF",
        builtin_icon!("PDFATTACH", "/assets/icons/underlay_layers.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "PEDIT",
        "Edit Polyline",
        builtin_icon!("PEDIT", "/assets/icons/modify_pedit.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "PERSP",
        "Persp",
        builtin_icon!("PERSP", "/assets/icons/persp.svg"),
        CommandCategory::View,
    ),
    builtin(
        "PLINE",
        "Polyline",
        Some(IconId::Polyline),
        CommandCategory::Draw,
    ),
    builtin("PLOT", "Plot", Some(IconId::Print), CommandCategory::File),
    builtin(
        "POINT",
        "Single Point",
        builtin_icon!("POINT", "/assets/icons/multipoint.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "POINTCLOUDATTACH",
        "Attach",
        builtin_icon!("POINTCLOUDATTACH", "/assets/icons/pc_attach.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "POLY",
        "Polygon - Inscribed",
        builtin_icon!("POLY", "/assets/icons/shapes/poly_i.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "POLYSOLID",
        "Polysolid",
        builtin_icon!("POLYSOLID", "/assets/icons/model/polysolid.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "POLY_C",
        "Polygon - Circumscribed",
        builtin_icon!("POLY_C", "/assets/icons/shapes/poly_c.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "POLY_E",
        "Polygon - Edge",
        builtin_icon!("POLY_E", "/assets/icons/shapes/poly_e.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "PRESSPULL",
        "Presspull",
        builtin_icon!("PRESSPULL", "/assets/icons/model/presspull.svg"),
        CommandCategory::Model,
    ),
    builtin("PRINT", "Print", Some(IconId::Print), CommandCategory::File),
    builtin(
        "PRINTALL",
        "Print All",
        builtin_icon!("PRINTALL", "/assets/icons/plot.svg"),
        CommandCategory::File,
    ),
    builtin(
        "PROPERTIES",
        "Properties",
        Some(IconId::Properties),
        CommandCategory::View,
    ),
    builtin(
        "PURGE",
        "Purge",
        builtin_icon!("PURGE", "/assets/icons/purge.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "PYRAMID",
        "Pyramid",
        builtin_icon!("PYRAMID", "/assets/icons/model/pyramid.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "QDIM",
        "Quick Dim",
        builtin_icon!("QDIM", "/assets/icons/qdim.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "QSAVE",
        "Quick Save",
        Some(IconId::Save),
        CommandCategory::File,
    ),
    builtin(
        "RAY",
        "Ray",
        builtin_icon!("RAY", "/assets/icons/ray.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "RECT",
        "Rectangle - Two Corners",
        Some(IconId::Rectangle),
        CommandCategory::Draw,
    ),
    builtin(
        "RECT_CEN",
        "Rectangle - Center",
        builtin_icon!("RECT_CEN", "/assets/icons/shapes/rect_cen.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "RECT_ROT",
        "Rectangle - Rotated",
        builtin_icon!("RECT_ROT", "/assets/icons/shapes/rect_rot.svg"),
        CommandCategory::Draw,
    ),
    builtin("REDO", "Redo", Some(IconId::Redo), CommandCategory::Utility),
    builtin(
        "REGION",
        "Region",
        builtin_icon!("REGION", "/assets/icons/region.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "REVCLOUD",
        "Rev Cloud",
        builtin_icon!("REVCLOUD", "/assets/icons/revcloud.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "REVERSE",
        "Reverse",
        builtin_icon!("REVERSE", "/assets/icons/modify_reverse.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "REVOLVE",
        "Revolve",
        builtin_icon!("REVOLVE", "/assets/icons/model/revolve.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "ROTATE",
        "Rotate",
        Some(IconId::Rotate),
        CommandCategory::Modify,
    ),
    builtin("SAVE", "Save", Some(IconId::Save), CommandCategory::File),
    builtin(
        "SAVEAS",
        "Save As",
        Some(IconId::SaveAs),
        CommandCategory::File,
    ),
    builtin(
        "SCALE",
        "Scale",
        Some(IconId::Scale),
        CommandCategory::Modify,
    ),
    builtin(
        "SCALELISTEDIT",
        "Scale List",
        builtin_icon!("SCALELISTEDIT", "/assets/icons/scale_list.svg"),
        CommandCategory::Annotate,
    ),
    builtin("SELECTALL", "Select All", None, CommandCategory::Selection),
    builtin(
        "SETBYLAYER",
        "Set to ByLayer",
        builtin_icon!("SETBYLAYER", "/assets/icons/modify_setbylayer.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "SHEETSET",
        "Sheet Set\nManager",
        builtin_icon!("SHEETSET", "/assets/icons/sheetset.svg"),
        CommandCategory::View,
    ),
    builtin(
        "SHELL",
        "Shell",
        builtin_icon!("SHELL", "/assets/icons/model/presspull.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "SPHERE",
        "Sphere",
        builtin_icon!("SPHERE", "/assets/icons/model/sphere.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "SPLINE",
        "Spline Fit",
        builtin_icon!("SPLINE", "/assets/icons/spline.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "SPLINECV",
        "Spline CV",
        builtin_icon!("SPLINECV", "/assets/icons/spline_cv.svg"),
        CommandCategory::Draw,
    ),
    builtin(
        "SPLINEDIT",
        "Edit Spline",
        builtin_icon!("SPLINEDIT", "/assets/icons/modify_splinedit.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "STRETCH",
        "Stretch",
        Some(IconId::Stretch),
        CommandCategory::Modify,
    ),
    builtin(
        "SUBTRACT",
        "Subtract",
        builtin_icon!("SUBTRACT", "/assets/icons/model/subtract.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "SWEEP",
        "Sweep",
        builtin_icon!("SWEEP", "/assets/icons/model/sweep.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "SYCONSTRAINT",
        "Symmetric",
        builtin_icon!("SYCONSTRAINT", "/assets/icons/constrain/symmetric.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "TABLE",
        "Table",
        builtin_icon!("TABLE", "/assets/icons/table.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "TCONSTRAINT",
        "Tangent",
        builtin_icon!("TCONSTRAINT", "/assets/icons/constrain/tangent.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "TEXT",
        "Text",
        builtin_icon!("TEXT", "/assets/icons/text.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "TOLERANCE",
        "Tolerance",
        builtin_icon!("TOLERANCE", "/assets/icons/tolerance.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "TOOLPALETTES",
        "Tool\nPalettes",
        builtin_icon!("TOOLPALETTES", "/assets/icons/tool_palettes.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "TORUS",
        "Torus",
        builtin_icon!("TORUS", "/assets/icons/model/torus.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "TRIM",
        "Trim",
        builtin_icon!("TRIM", "/assets/icons/trim.svg"),
        CommandCategory::Modify,
    ),
    builtin(
        "UCSICON",
        "UCS\nIcon",
        builtin_icon!("UCSICON", "/assets/icons/ucs_icon.svg"),
        CommandCategory::View,
    ),
    builtin(
        "UNDERLAYLAYERS",
        "Underlay\nLayers",
        builtin_icon!("UNDERLAYLAYERS", "/assets/icons/underlay_layers.svg"),
        CommandCategory::Insert,
    ),
    builtin("UNDO", "Undo", Some(IconId::Undo), CommandCategory::Utility),
    builtin(
        "UNGROUP",
        "Ungroup",
        builtin_icon!("UNGROUP", "/assets/icons/ungroup.svg"),
        CommandCategory::Manage,
    ),
    builtin(
        "UNION",
        "Union",
        builtin_icon!("UNION", "/assets/icons/model/union.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "UNISOLATEOBJECTS",
        "End Object Isolation",
        None,
        CommandCategory::Selection,
    ),
    builtin(
        "UOSNAP",
        "Snap to\nUnderlays",
        builtin_icon!("UOSNAP", "/assets/icons/snap_underlays.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "VCONSTRAINT",
        "Vertical",
        builtin_icon!("VCONSTRAINT", "/assets/icons/constrain/vertical.svg"),
        CommandCategory::Parametric,
    ),
    builtin(
        "VERTICAL",
        "Tile\nVert.",
        builtin_icon!("VERTICAL", "/assets/icons/tile_vert.svg"),
        CommandCategory::View,
    ),
    builtin(
        "VIEW",
        "Iso",
        builtin_icon!("VIEW", "/assets/icons/view_iso.svg"),
        CommandCategory::View,
    ),
    builtin(
        "VISUALSTYLES",
        "Gouraud Shaded + Edges",
        builtin_icon!("VISUALSTYLES", "/assets/icons/solid.svg"),
        CommandCategory::View,
    ),
    builtin(
        "VPJOIN",
        "Join",
        builtin_icon!("VPJOIN", "/assets/icons/vports_join.svg"),
        CommandCategory::View,
    ),
    builtin(
        "VPORTS",
        "Restore",
        builtin_icon!("VPORTS", "/assets/icons/vports_restore.svg"),
        CommandCategory::View,
    ),
    builtin(
        "WEDGE",
        "Wedge",
        builtin_icon!("WEDGE", "/assets/icons/model/wedge.svg"),
        CommandCategory::Model,
    ),
    builtin(
        "WIPEOUT",
        "Wipeout",
        builtin_icon!("WIPEOUT", "/assets/icons/wipeout.svg"),
        CommandCategory::Annotate,
    ),
    builtin(
        "XATTACH",
        "Attach XREF",
        builtin_icon!("XATTACH", "/assets/icons/blocks/insert.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "XCLIP",
        "Clip",
        builtin_icon!("XCLIP", "/assets/icons/xclip.svg"),
        CommandCategory::Insert,
    ),
    builtin(
        "XLINE",
        "Construction Line",
        builtin_icon!("XLINE", "/assets/icons/xline.svg"),
        CommandCategory::Draw,
    ),
    builtin("ZOOM", "Zoom", Some(IconId::Zoom), CommandCategory::View),
];
